/**
 * @file gen_offsets.c
 * @brief Generates assembly constants for struct task field offsets
 *
 * This file is compiled to assembly and the resulting .s file is processed
 * to extract offset constants. This ensures assembly code stays in sync
 * with the C struct definition, preventing hard-coded offset bugs.
 */

#include <arch/tss.h>
#include <proc/task.h>
#include <signal.h>
#include <types.h>
#include <utils/kmacro.h>

/**
 * Define an offset constant using inline assembly.
 * The %c constraint outputs the compile-time constant.
 */
#define DEFINE_OFFSET(structure, field)                                                            \
	__asm__ volatile(".ascii \"\\n.equ TASK_" #field "_OFFSET, %c0\\n\""                       \
			 :                                                                         \
			 : "i"(offsetof(structure, field)))

#define DEFINE_TSS_OFFSET(structure, field)                                                        \
	__asm__ volatile(".ascii \"\\n.equ TSS_ESP0_OFFSET, %c0\\n\""                              \
			 :                                                                         \
			 : "i"(offsetof(structure, field)))

void generate_offsets(void)
{
	__asm__ volatile(".ascii \"# Auto-generated file - DO NOT EDIT\\n\"");
	__asm__ volatile(".ascii \"# Generated by tools/gen_offsets.c\\n\"");
	__asm__ volatile(".ascii \"#\\n\"");
	__asm__ volatile(
		".ascii \"# This file contains offset constants for struct task fields.\\n\"");
	__asm__ volatile(
		".ascii \"# These offsets must match the C struct definition in include/proc/task.h\\n\"");

	DEFINE_OFFSET(struct task, esp);
	DEFINE_OFFSET(struct task, cr3);
	DEFINE_OFFSET(struct task, kernel_stack_pointer);

	__asm__ volatile(".ascii \"\\n# TSS offsets\\n\"");
	DEFINE_TSS_OFFSET(struct tss, esp0);
}
